from __future__ import annotations

from datetime import datetime
from typing import Protocol

from pulseforge.domain.models import Document, Event, Source


class IntelligenceRepository(Protocol):
    def save_documents(self, documents: list[Document]) -> list[Document]: ...
    def save_events(self, events: list[Event]) -> list[Event]: ...
    def get_source(self, source_id: str) -> Source | None: ...
    def list_events(self) -> list[Event]: ...
    def mark_document_stage(
        self, document_id: str, stage: str, *, error: str | None = None
    ) -> None: ...
    def documents_between(self, workspace_id: str, start: datetime, end: datetime) -> list[Document]: ...
